/* The Singapore trip list — the island's history district by district, and
 * the Grand Prix that is the reason for going. Separate page, separate
 * kv_state row, so ticking off Marseille documentaries and Marina Bay ones
 * never share a progress bar. The engine and the item schema are in
 * checklist.js.
 *
 * Most of this is in English, unlike the French list: there is little French
 * material on Singapore beyond the first few items. Formula 1 is the
 * exception — it has a francophone press, so that section is nearly half in
 * French.
 */

const SECTIONS = [
  {
    title: '🇸🇬 Singapour — histoire & quartiers',
    blurb: 'Ce que l’île était avant la carte postale, puis un quartier à la fois. Le gros est en anglais : la matière française sur Singapour s’arrête à peu près aux quatre premiers.',
    items: [
      { id: 'sg-eb', lang: 'fr', kind: '▶️', sec: 5415, title: 'Échappées belles — « Surprenante Singapour »',
        desc: 'Le tour d’horizon à faire en premier : quartiers, communautés, et la ville-jardin vue de près. France 5, en français.', url: 'https://www.youtube.com/watch?v=dIah7-IBQcs' },
      { id: 'sg-paradis', lang: 'fr', kind: '▶️', sec: 1866, title: 'Singapour, voyage dans un paradis artificiel',
        desc: 'L’envers du décor : le luxe, l’ordre, et ce qu’ils coûtent. Utile avant d’arriver avec des yeux de touriste.', url: 'https://www.youtube.com/watch?v=2cEXp00oKHk' },
      { id: 'sg-finary', lang: 'fr', kind: '▶️', sec: 1508, title: 'Singapour : la dictature la plus heureuse',
        desc: 'Comment une île sans ressources est devenue ça — par la chaîne que tu suis déjà.', url: 'https://www.youtube.com/watch?v=r9clcxQWiJo' },
      { id: 'sg-f24', lang: 'fr', kind: '▶️', sec: 341, title: 'Singapour : 60 ans de prospérité, mais à quel prix ?',
        desc: 'Cinq minutes pour la question qui traverse tout le reste. FRANCE 24.', url: 'https://www.youtube.com/watch?v=wcg88HGsg-Q' },
      { id: 'sg-avant-raffles', lang: 'en', kind: '▶️', sec: 247, title: 'A Thriving Singapore Before Stamford Raffles, From Orang Laut Descendants',
        desc: 'L’île avait une histoire avant 1819, et ce sont les descendants des Orang Laut qui la racontent. Quatre minutes.', url: 'https://www.youtube.com/watch?v=_PC7pM3DJYQ' },
      { id: 'sg-separation', lang: 'en', kind: '▶️', sec: 2820, title: 'Secrets, Betrayals: How Singapore’s Split From Malaysia Was Sealed',
        desc: 'La séparation de 1965, par ceux qui étaient dans la pièce — l’événement fondateur du pays.', url: 'https://www.youtube.com/watch?v=mwG-Dp00sDY' },
      { id: 'sg-lky', lang: 'en', kind: '▶️', sec: 2812, title: 'Lee Kuan Yew: In His Own Words',
        desc: 'L’homme qui a dessiné le pays, dans ses propres mots. À regarder après le documentaire Finary, pas avant.', url: 'https://www.youtube.com/watch?v=whRN-CJZDr0' },
      { id: 'sg-coastlines', lang: 'en', kind: '▶️', sec: 2851, title: 'How Have Singapore’s Coastlines Changed Over The Years?',
        desc: 'Un quart de l’île n’existait pas : la poldérisation explique la forme de la carte et l’emplacement de Marina Bay.', url: 'https://www.youtube.com/watch?v=4nP7q5k1eTU' },
      { id: 'sg-chinatown', lang: 'en', kind: '▶️', sec: 474, title: 'Up Your Alley: Singapore’s Chinatown and its hidden gems',
        desc: 'Chinatown par ses ruelles plutôt que par ses devantures. Sept minutes, à voir la veille d’y aller.', url: 'https://www.youtube.com/watch?v=LX4ZMPA14jo' },
      { id: 'sg-clans', lang: 'en', kind: '▶️', sec: 2883, title: 'Uncovering Legacy Of Chinese Clan Houses In Singapore',
        desc: 'Les maisons de clan : comment les migrants chinois se sont organisés par dialecte et par village d’origine.', url: 'https://www.youtube.com/watch?v=SpstluYZ71U' },
      { id: 'sg-little-india', lang: 'en', kind: '▶️', sec: 1416, title: 'Singapore’s Little India: One Of World’s Coolest Neighbourhoods',
        desc: 'Little India, ses commerces et son dimanche — le jour où le quartier appartient aux travailleurs migrants.', url: 'https://www.youtube.com/watch?v=t3pkrA4HVxQ' },
      { id: 'sg-kampong-glam', lang: 'en', kind: '▶️', sec: 1152, title: 'The Untold Stories of Kampong Glam, Singapore',
        desc: 'Le quartier malais-arabe autour de la mosquée du Sultan : sultanat, textiles, et gentrification.', url: 'https://www.youtube.com/watch?v=XHXgtGZbulY' },
      { id: 'sg-katong', lang: 'en', kind: '▶️', sec: 921, title: 'Uncover the Secrets of Joo Chiat / Katong Singapore',
        desc: 'Katong-Joo Chiat, cœur peranakan : maisons de ville colorées et laksa de Katong.', url: 'https://www.youtube.com/watch?v=IaKPR91705w' },
      { id: 'sg-peranakan', lang: 'en', kind: '▶️', sec: 1191, title: 'Lost in Peranakan Paradise',
        desc: 'La culture peranakan — chinoise, malaise, et ni l’une ni l’autre. Le fil à suivre à Katong et au musée.', url: 'https://www.youtube.com/watch?v=mUAcAPuUI40' },
      { id: 'sg-tiong-bahru', lang: 'en', kind: '▶️', sec: 1007, title: 'Uncover the Secrets of Tiong Bahru Singapore',
        desc: 'Le premier quartier de logements publics, art déco des années 1930, devenu le plus couru de la ville.', url: 'https://www.youtube.com/watch?v=fDR4HPC4qfw' },
      { id: 'sg-geylang', lang: 'en', kind: '▶️', sec: 1375, title: 'Geylang: Not Just The Seedy Underbelly Of Singapore',
        desc: 'Geylang : quartier rouge, temples et meilleurs restaurants de la ville, dans les mêmes rues.', url: 'https://www.youtube.com/watch?v=52P1W9ZOMdA' },
      { id: 'sg-orchard', lang: 'en', kind: '▶️', sec: 2820, title: 'History Of 1960s Orchard Road: Anthems, Boogie & Cabaret',
        desc: 'Orchard Road avant les centres commerciaux — vergers, cabarets et cinémas.', url: 'https://www.youtube.com/watch?v=vJfqeMU9v8s' },
      { id: 'sg-hdb', lang: 'en', kind: '▶️', sec: 1377, title: 'The Hidden Histories Of Singapore’s HDB Flats',
        desc: 'Où vivent 80 % des Singapouriens, et pourquoi les quartiers sont composés comme ils le sont.', url: 'https://www.youtube.com/watch?v=UyTumSJbQ1g' },
      { id: 'sg-shophouses', lang: 'en', kind: '▶️', sec: 2728, title: 'Shophouses Transformed: Preserving Our Heritage',
        desc: 'La shophouse, forme urbaine de toute la vieille ville : à quoi ressemble l’intérieur et ce qu’il en reste.', url: 'https://www.youtube.com/watch?v=FP3ceLXpvzk' },
      { id: 'sg-hawker', lang: 'en', kind: '▶️', sec: 2881, title: 'A History Of Singapore Hawker Culture: From Food To Architecture',
        desc: 'Des marchands de rue aux hawker centres — l’histoire de la façon dont le pays mange, classée à l’UNESCO.', url: 'https://www.youtube.com/watch?v=pw1oLexEGzo' },
      { id: 'sg-chronicles', lang: 'en', kind: '🎙️', approx: 2340, show: 'Chronicles of Old Singapore', title: 'Chronicles of Old Singapore',
        desc: 'L’historien Loh Kah Seng interroge ceux qui y étaient : bases britanniques, migrants teochew, quartiers disparus.', url: 'https://podcasts.apple.com/fr/podcast/id1768545888' },
      { id: 'sg-biblioasia', lang: 'en', kind: '🎙️', approx: 2280, show: 'BiblioAsia Podcast', title: 'BiblioAsia (National Library Board)',
        desc: 'Le podcast de la Bibliothèque nationale : une source de première main par épisode, souvent sur la nourriture et les métiers.', url: 'https://podcasts.apple.com/fr/podcast/id1688142751' },
    ],
  },
  {
    title: '🏎️ Formule 1 — Marina Bay, de nuit',
    blurb: 'La raison du voyage : le circuit, la course la plus dure de la saison, et son meilleur scandale. Mieux servi en français que le reste de Singapour — la F1 a sa presse francophone.',
    items: [
      { id: 'f1-circuit-guide', lang: 'en', kind: '▶️', sec: 164, title: 'F1 Circuit Guide: Marina Bay, Singapore',
        desc: 'Deux minutes pour avoir le tracé en tête avant d’y être : 19 virages, des murs partout.', url: 'https://www.youtube.com/watch?v=YeSCW07p-CU' },
      { id: 'f1-overcut', lang: 'fr', kind: '▶️', sec: 419, title: 'Un tour de circuit à Singapour : analyse',
        desc: 'Le même tour, commenté virage par virage en français. À enchaîner avec le guide officiel.', url: 'https://www.youtube.com/watch?v=q8BThEycrr4' },
      { id: 'f1-birdseye', lang: 'en', kind: '▶️', sec: 141, title: 'A Bird’s Eye View of the Marina Bay Street Circuit',
        desc: 'Le circuit vu du ciel — utile pour situer les tribunes et la ville autour.', url: 'https://www.youtube.com/watch?v=6UQY4wnyBAE' },
      { id: 'f1-decade', lang: 'en', kind: '▶️', sec: 210, title: 'A Decade Under The Lights',
        desc: 'Dix ans de courses de nuit en trois minutes : pourquoi cette manche-là ne ressemble à aucune autre.', url: 'https://www.youtube.com/watch?v=jryGPedPAqA' },
      { id: 'f1-1966', lang: 'en', kind: '▶️', sec: 398, title: '1966 Singapore Grand Prix',
        desc: 'Le Grand Prix de Singapour existait avant 2008 : Thomson Road, sans murs ni projecteurs. Archives de la Bibliothèque nationale.', url: 'https://www.youtube.com/watch?v=gPiSpg3t4zg' },
      { id: 'f1-crashgate-fr', lang: 'fr', kind: '▶️', sec: 788, title: 'Le Crashgate : le scandale qui a fait vaciller la F1',
        desc: 'Singapour 2008 : un équipier envoyé dans le mur sur ordre. La meilleure histoire du circuit, en français.', url: 'https://www.youtube.com/watch?v=3p2Pb9P1tFE' },
      { id: 'f1-crashgate-en', lang: 'en', kind: '▶️', sec: 994, title: 'Crashgate Simplified — A Detailed Account',
        desc: 'La même affaire en anglais et en détail : à écouter après la version française, l’histoire étant déjà connue.', url: 'https://www.youtube.com/watch?v=27EgIi_SXD0' },
      { id: 'f1-track-built', lang: 'en', kind: '▶️', sec: 617, title: 'How the Singapore F1 Track is Built',
        desc: 'Comment on transforme des rues en circuit chaque année, puis on remet la ville en place.', url: 'https://www.youtube.com/watch?v=G9ofgRUsQUM' },
      { id: 'f1-lighting', lang: 'en', kind: '▶️', sec: 140, title: 'Lighting the F1 Singapore Grand Prix',
        desc: 'L’éclairage qui rend la course possible : 1 700 projecteurs pour un jour artificiel.', url: 'https://www.youtube.com/watch?v=almA52FXegM' },
      { id: 'f1-rosberg', lang: 'en', kind: '▶️', sec: 837, title: 'How to Master the Singapore GP',
        desc: 'Un champion du monde explique le pilotage ici : freinages, bosses, et pourquoi on y perd 3 kg.', url: 'https://www.youtube.com/watch?v=KXsiUUfGiLY' },
      { id: 'f1-toughest', lang: 'en', kind: '▶️', sec: 247, title: 'Why Singapore is the Toughest Challenge for F1 Drivers',
        desc: 'Chaleur, humidité, deux heures sans répit — ce que la télévision ne montre pas.', url: 'https://www.youtube.com/watch?v=x0ZkPDUDpZ8' },
      { id: 'f1-heat', lang: 'en', kind: '▶️', sec: 600, title: 'Facing the Heat: Formula 1 in Singapore',
        desc: 'Côté équipe : comment un stand se prépare à la manche la plus physique de l’année.', url: 'https://www.youtube.com/watch?v=OzBUUkYSSJo' },
      { id: 'f1-febreau', lang: 'fr', kind: '▶️', sec: 4143, title: 'Julien Fébreau — les secrets de la voix de la F1',
        desc: 'L’homme qui commente la F1 en français, sur son métier. Une heure d’écoute confortable.', url: 'https://www.youtube.com/watch?v=wSrTWt3D9HE' },
      { id: 'f1-idreau', lang: 'fr', kind: '▶️', sec: 7718, title: 'Les secrets des paddocks de F1 — Cool Room avec Julien Fébreau',
        desc: 'Deux heures de paddock racontées de l’intérieur : le format long à garder pour l’avion.', url: 'https://www.youtube.com/watch?v=OvTWn6PXqGs' },
      { id: 'f1-ocon', lang: 'fr', kind: '▶️', sec: 3127, title: 'Esteban Ocon : la vraie vie de pilote de F1',
        desc: 'Un pilote français, en français, sur ce que le métier est réellement. Clique / CANAL+.', url: 'https://www.youtube.com/watch?v=PGbVGe86eeQ' },
      { id: 'f1-motorsport-fr', lang: 'fr', kind: '▶️', sec: 180, title: 'Inside GP circuit Singapour',
        desc: 'Trois minutes dans le circuit, commentées en français.', url: 'https://www.youtube.com/watch?v=8WvubpKsPB8' },
      { id: 'f1-paddock-rmc', lang: 'fr', kind: '🎙️', approx: 1800, show: 'Le Paddock RMC', title: 'Le Paddock RMC',
        desc: 'Le rendez-vous F1 de RMC, une demi-heure par épisode — le plus régulier des podcasts F1 en français.', url: 'https://podcasts.apple.com/fr/podcast/id1733871991' },
      { id: 'f1-oeil-paddock', lang: 'fr', kind: '🎙️', approx: 600, show: 'L’Œil du Paddock', title: 'L’Œil du Paddock',
        desc: 'Dix minutes d’actualité F1 en français, presque tous les jours. Le format parfait pour un trajet.', url: 'https://podcasts.apple.com/fr/podcast/id1678483509' },
      { id: 'f1-refait', lang: 'fr', kind: '🎙️', approx: 3660, show: 'On Refait la F1 - Les fanas du Paddock !', title: 'On Refait la F1 — Les fanas du Paddock !',
        desc: 'Débrief d’après-course entre passionnés, une heure, en français.', url: 'https://podcasts.apple.com/fr/podcast/id1740367135' },
      { id: 'f1-nation', lang: 'en', kind: '🎙️', approx: 1920, show: 'F1 Nation', title: 'F1 Nation',
        desc: 'Le podcast officiel : aperçu avant la course, débrief après. Celui à écouter la semaine de Singapour.', url: 'https://podcasts.apple.com/fr/podcast/id1510367515' },
      { id: 'f1-grid', lang: 'en', kind: '🎙️', approx: 2700, show: 'F1 Beyond The Grid', title: 'F1 Beyond The Grid',
        desc: 'Longs entretiens avec pilotes et patrons d’écurie — 444 épisodes de rattrapage.', url: 'https://podcasts.apple.com/fr/podcast/id1405972616' },
    ],
  },
];

initChecklist({ sections: SECTIONS, kvKey: 'singapore-checklist', surface: 'singapore' });
