name = "ecoute-spotify"
main = "worker.js"
compatibility_date = "2026-07-01"
workers_dev = true

[[kv_namespaces]]
binding = "STATE"
id = "5f5a3f31f20f4cc0b5fee1383406fd9b"

[triggers]
crons = ["*/2 * * * *"]

[observability]
enabled = true
